config = {
    'API_KEY': 'ENTER API KEY',
    'FROM_EMAIL': 'ENTER SENDER EMAIL',
    'FROM_PASSWORD': 'ENTER SENDER EMAIL GOOGLE APP PASSWORD',
    'TO_EMAIL': 'ENTER TARGET EMAIL',
    'TEAMS': ['ENTER', 'TEAM', 'KEYS']
}